### ISSUE TITLE
Religion: Limit the number of pantheons that can be founded to 8

### ISSUE THREAD

**Issue by rhin123** [rhin123/OpenCiv#49]
Currently, all players can pick a pantheon. We want to limit this number to 8, since ```CityReligionFollowersUpdatePacket``` only handles a list of 8 unique religion followers.

We would modify the ```onNextTurn()``` method in the Server's ```PlayerReligion``` class to handle this. 
Where we would iterate over ```Server.getInstance().getPlayers() ... getReligion()```with a ```getPickedBonuses() > 0``` to get the current number of pantheons.

**Comment by gfreitag** [comment]
Hi, I'd like to give this a shot. 👋

**Comment by rhin123** [comment]
> Hi, I'd like to give this a shot. 👋

Okay sounds good! Let me know if you have any questions.

**Comment by gfreitag** [comment]
> Okay sounds good! Let me know if you have any questions.

Actually, I do have a quick one. I'm not super familiar with eclipse, how do I run your game from it? I've imported it as an existing gradle project, but I'm not sure how to launch it.

**Comment by rhin123** [comment]
> > Okay sounds good! Let me know if you have any questions.
> 
> Actually, I do have a quick one. I'm not super familiar with eclipse, how do I run your game from it? I've imported it as an existing gradle project, but I'm not sure how to launch it.

To get the game running you would run the OpenCiv-lwjgl3 ```Lwjgl3Launcher.java``` class & the OpenCiv-server ```Server.jar``` To start the Client & Server/

Right click -> Run as -> Java Application
![run_client](https://user-images.githubusercontent.com/6068039/148315501-4f7f38c5-6f48-4289-820a-63b976298e92.png)

Right click -> Run as -> Java Application
![run_server](https://user-images.githubusercontent.com/6068039/148315505-e3511fbf-d4e5-47d4-bebe-810369c017d0.png)

**Comment by gfreitag** [comment]
Very helpful! By chance, which version of java are you using?

**Comment by rhin123** [comment]
> Very helpful! By chance, which version of java are you using?
The project uses java 11+

**Comment by gfreitag** [comment]
Argh, I would really like to start on the issue, but Eclipse keeps giving me problems. I set java my execution environment to Java 14, to no avail. Eclipse keeps complaining about my native dependencies. This feels like an issue on my end, but is there anything else that I should have installed on my machine to make it work? Here's the error I get whenever I try to run the launcher:
<img width="1269" alt="Screen Shot 2022-01-07 at 1 04 31 PM" src="https://user-images.githubusercontent.com/16789649/148607584-59674388-31cb-460f-8009-688c1550ccc2.png">
does it look familiar?

**Comment by rhin123** [comment]
> Argh, I would really like to start on the issue, but Eclipse keeps giving me problems. I set java my execution environment to Java 14, to no avail. Eclipse keeps complaining about my native dependencies. This feels like an issue on my end, but is there anything else that I should have installed on my machine to make it work? Here's the error I get whenever I try to run the launcher: does it look familiar?

That's really odd. What OS are you on? 
Check your java build path in your project properties, and play around with the version your using.
This is what mine looks like,
![image](https://user-images.githubusercontent.com/6068039/148609675-b7205861-2d89-4781-8bdf-40e8bab86580.png)

If that doesn't work I'd also try installing JDK 1.8 or JDK 11, and change to execution environment to them.
https://www.oracle.com/java/technologies/javase/javase8-archive-downloads.html
https://www.oracle.com/java/technologies/javase/jdk11-archive-downloads.html

I'd like to help you more but I've never experienced that error before.
Also, to note is that OpenJDK isn't compatible with LibGDX.

**Comment by rhin123** [comment]
Could you provide that log file?

**Comment by gfreitag** [comment]
> Could you provide that log file?

sure.
[hs_err_pid2838.log](https://github.com/rhin123/OpenCiv/files/7834015/hs_err_pid2838.log)

Tried a number of things, different java versions (11), and even updated my Eclipse and did a hardware diagnostic on my machine. Not sure what's up!

**Comment by rhin123** [comment]
> > Could you provide that log file?
> 
> sure. [hs_err_pid2838.log](https://github.com/rhin123/OpenCiv/files/7834015/hs_err_pid2838.log)
> 
> Tried a number of things, different java versions (11), and even updated my Eclipse and did a hardware diagnostic on my machine. Not sure what's up!

Thank you! I've pushed some changes fixing what I suspect might be causing the issue. Do a ```git pull``` & let me know if it did anything. I appreciate your patience.

**Comment by gfreitag** [comment]
> > > Could you provide that log file?
> > 
> > 
> > sure. [hs_err_pid2838.log](https://github.com/rhin123/OpenCiv/files/7834015/hs_err_pid2838.log)
> > Tried a number of things, different java versions (11), and even updated my Eclipse and did a hardware diagnostic on my machine. Not sure what's up!
> 
> Thank you! I've pushed some changes fixing what I suspect might be causing the issue. Do a `git pull` & let me know if it did anything. I appreciate your patience. If it still doesn't work disable the rest of the config settings, vsync, ect. in `Lwjgl3Launcher.java`

Darn, I'm still getting the same issue (sorry for the slow response on my end). Pulled and tried to disable anything config related in Lwjgl3Launcher.java, same in Civilization.java. It's too bad because I think you have something cool here that would be fun to work on! I'll try to figure out what's going on in my own time as well. I'll also try some other IDEs in case Eclipse is the one causing me problems.

**Comment by rhin123** [comment]
I'm sorry we weren't able to figure it out. Once I get a mac I'll definitely look into that error.
